title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://shadow-s09g.github.io/leetcode-fast-pass

aux_links:
   s09g Repository: https://github.com/s09g